export const CAREER_AREAS = [
  {
    slug: "welding-fabrication",
    title: "Welding & Fabrication",
    icon: "welding",
    eyebrow: "Career Area",
    summary:
      "Build complex architectural and structural metalwork with a team that values accuracy, consistency, and pride in every finished piece.",
    responsibilities: [
      "Interpret fabrication drawings, shop details, and production requirements.",
      "Complete welding, fitting, layout, and fabrication work to project specifications.",
      "Maintain dimensional accuracy and finish quality throughout production.",
      "Coordinate with supervisors, quality teams, and adjacent production departments.",
      "Follow all workplace safety, equipment, and material-handling procedures.",
    ],
    qualifications: [
      "Relevant welding, fitting, or metal-fabrication experience.",
      "Ability to read drawings, measurements, and fabrication documentation.",
      "Strong attention to detail and commitment to safe work practices.",
      "Ability to work independently and as part of a production team.",
    ],
  },
  {
    slug: "cnc-laser-waterjet",
    title: "CNC, Laser & Waterjet",
    icon: "machine",
    eyebrow: "Career Area",
    summary:
      "Use advanced cutting and machining technology to transform detailed production information into accurate, repeatable components.",
    responsibilities: [
      "Set up and operate CNC, laser, waterjet, or related production equipment.",
      "Review drawings, cut files, nesting plans, and material specifications.",
      "Monitor tolerances, machine performance, and finished-part quality.",
      "Complete routine inspections, maintenance checks, and production records.",
      "Work closely with engineering, fabrication, and quality-control teams.",
    ],
    qualifications: [
      "Experience with CNC or automated metal-processing equipment is preferred.",
      "Comfort reading technical drawings and working with precise measurements.",
      "Strong mechanical awareness and problem-solving ability.",
      "Commitment to safety, quality, and organized production practices.",
    ],
  },
  {
    slug: "engineering-drafting",
    title: "Engineering & Drafting",
    icon: "drafting",
    eyebrow: "Career Area",
    summary:
      "Translate architectural intent and project requirements into coordinated, buildable information for fabrication and installation.",
    responsibilities: [
      "Prepare and review drawings, models, details, and production information.",
      "Coordinate technical requirements with project, fabrication, and field teams.",
      "Identify constructability issues and support practical design solutions.",
      "Maintain drawing accuracy, revision control, and project documentation.",
      "Support material planning, procurement, and production coordination.",
    ],
    qualifications: [
      "Education or experience in engineering, drafting, architecture, or a related field.",
      "Working knowledge of relevant CAD, BIM, or modelling software.",
      "Strong technical communication and document-management skills.",
      "Ability to manage detailed information across multiple project stakeholders.",
    ],
  },
  {
    slug: "project-management",
    title: "Project Management",
    icon: "clipboard",
    eyebrow: "Career Area",
    summary:
      "Lead complex metalwork projects by connecting clients, consultants, production teams, suppliers, and field operations.",
    responsibilities: [
      "Coordinate project scope, schedule, budget, procurement, and deliverables.",
      "Maintain clear communication with clients, consultants, and internal teams.",
      "Track drawings, approvals, changes, risks, and production milestones.",
      "Support issue resolution from preconstruction through installation and closeout.",
      "Maintain organized project documentation and reporting.",
    ],
    qualifications: [
      "Experience in construction, manufacturing, architectural metalwork, or a related environment.",
      "Strong planning, communication, and stakeholder-management skills.",
      "Ability to manage priorities, deadlines, and technical documentation.",
      "Commercial awareness and a disciplined approach to project controls.",
    ],
  },
  {
    slug: "quality-control-inspection",
    title: "Quality Control & Inspection",
    icon: "quality",
    eyebrow: "Career Area",
    summary:
      "Protect the standard behind every Mariani project through disciplined inspection, documentation, and continuous quality improvement.",
    responsibilities: [
      "Inspect materials, fabricated components, welds, finishes, and assemblies.",
      "Verify dimensions and requirements against drawings and specifications.",
      "Record findings, non-conformances, corrective actions, and inspection results.",
      "Coordinate with production teams to resolve quality issues efficiently.",
      "Support quality procedures, traceability, and continuous improvement.",
    ],
    qualifications: [
      "Experience in quality control, inspection, fabrication, or manufacturing.",
      "Ability to read drawings, specifications, and inspection documentation.",
      "Strong observational, measurement, and record-keeping skills.",
      "Relevant inspection certifications are considered an asset.",
    ],
  },
  {
    slug: "finishing-assembly-production",
    title: "Finishing, Assembly & Production",
    icon: "production",
    eyebrow: "Career Area",
    summary:
      "Bring fabricated components together through careful preparation, finishing, assembly, packaging, and production support.",
    responsibilities: [
      "Complete finishing, assembly, preparation, and production-support activities.",
      "Review work instructions, drawings, and quality requirements.",
      "Handle materials and finished components safely and carefully.",
      "Maintain clean, organized, and efficient work areas.",
      "Coordinate with fabrication, finishing, quality, and shipping teams.",
    ],
    qualifications: [
      "Production, manufacturing, assembly, or finishing experience is preferred.",
      "Strong attention to detail and respect for finished-product quality.",
      "Ability to use hand tools, production equipment, and measuring devices safely.",
      "Dependable, organized, and comfortable working in a team environment.",
    ],
  },
];

export const JOBS_BY_REGION = {
  canada: [
    {
      slug: "drawing-checker",
      title: "Drawing Checker",
      location: "Canada",
      type: "Full-Time",
      department: "Engineering & Drafting",
      eyebrow: "Canada Opportunity",
      summary:
        "Review engineering drawings and specifications for accuracy, compliance, quality, and alignment with project requirements.",
      responsibilities: [
        "Review and verify the accuracy of engineering drawings and specifications.",
        "Ensure compliance with industry codes, regulations, and project requirements.",
        "Collaborate with engineers, architects, and designers to resolve discrepancies and design issues.",
        "Create and maintain drawing logs and documentation for all revisions and changes.",
        "Communicate with project managers to ensure the timely and accurate delivery of drawings.",
        "Conduct on-site inspections to verify compliance with drawings and specifications.",
        "Provide technical support and guidance to junior staff members.",
        "Stay up to date with industry trends, technologies, and best practices related to drawing checking and document control.",
        "Apply thorough knowledge and understanding of CWB and AWS welding processes and welding symbols.",
        "Identify and correct errors, omissions, or discrepancies in drawings.",
        "Participate in the development and implementation of quality-control procedures for drawings.",
      ],
      qualifications: [
        "Proficiency in reading and interpreting engineering drawings.",
        "Knowledge of CAD software and the ability to use it to check drawings.",
        "Attention to detail and the ability to identify errors and discrepancies.",
        "Communication skills to liaise with engineers and designers to resolve issues.",
        "Understanding of industry standards and regulations related to drawings and design.",
        "Experience in a similar role and the ability to work independently.",
        "Ability to prioritize tasks and meet tight deadlines.",
        "Willingness to learn and adapt to new technologies and processes.",
      ],
    },
    {
      slug: "manual-machinist",
      title: "Manual Machinist",
      location: "Canada",
      type: "Full-Time",
      department: "Machining",
      eyebrow: "Canada Opportunity",
      summary:
        "Perform precise machining operations using manual and numerically controlled equipment to produce high-quality components from a range of metals.",
      responsibilities: [
        "Use various types of manual and numerically controlled machine-shop equipment, including cylindrical and surface grinders, burring equipment, lathes, and honing equipment.",
        "Perform machining operations on materials including steel, aluminum, stainless steel, brass, and bronze.",
        "Work from specifications and design criteria, including verbal instructions, drawings, and blueprints, and perform standard shop computations relating to work dimensions and tooling.",
        "Use a wide variety of precision measuring instruments and maintain accurate dimensional tolerances based on drawings.",
        "Improvise production aids as necessary to facilitate operations.",
        "Rework and calibrate production parts, assemblies, and machine tooling as required, checking each component for accuracy as it comes off the machine.",
        "Maintain thorough knowledge of all applicable safety requirements and considerations.",
        "Provide all required reports and correspondence.",
        "Perform other related duties as assigned by the supervisor.",
        "Operate manual lathes, mills, and grinders.",
        "Read and interpret blueprints and technical drawings.",
        "Produce high-quality parts and components according to specifications.",
        "Perform routine maintenance on machining equipment.",
        "Ensure all work is completed in a timely and efficient manner.",
        "Adhere to all safety protocols and guidelines.",
        "Keep accurate records of work, including measurements and materials used.",
        "Collaborate with team members to complete projects.",
        "Troubleshoot and resolve machining issues.",
        "Inspect finished products for quality and accuracy.",
        "Set up and adjust machinery for different tasks.",
        "Maintain a clean and organized work area.",
        "Follow standard operating procedures and best practices.",
        "Communicate effectively with supervisors and colleagues.",
        "Participate in continuous-improvement initiatives.",
        "Train and mentor junior machinists as needed.",
        "Ensure compliance with company policies and regulations.",
        "Monitor inventory levels and request supplies as needed.",
        "Assist in developing new machining techniques.",
        "Provide feedback on design and manufacturing processes.",
      ],
      qualifications: [],
    },
    {
      slug: "assistant-project-coordinator",
      title: "Assistant Project Coordinator",
      location: "Canada",
      type: "Full-Time",
      department: "Engineering",
      eyebrow: "Canada Opportunity",
      summary:
        "Support engineering project delivery through coordination, tracking, documentation, procurement assistance, construction support, and project closeout.",
      responsibilities: [
        "Maintain and monitor engineering activities and progress trackers, project plans, and project schedules.",
        "Coordinate with design consultants, engineers, project representatives, internal departments, and authority agencies to establish design deliverable requirements for submission.",
        "Document and follow up on important actions and decisions from meetings.",
        "Maintain regular communication with the active team and business stakeholders to ensure necessary and appropriate steps are taken to resolve difficulties that may impede progress or compromise achievement of the project's objectives.",
        "Prepare and maintain an engineering cost tracker for new projects to record and track all costs associated with engineering activities.",
        "Maintain filing and document control for engineering documents.",
        "Assist the procurement agent with the technical inputs required to facilitate equipment procurement and the hiring of external engineering consultants and subcontractors.",
        "Support the implementation of design services during construction, including requests for information, shop drawing reviews, non-conformance report resolution, and design changes.",
        "Assist with overall project closeout, including coordinating with consultants to provide completion documents and as-builts, correcting engineering deficiencies, and maintaining and filing all closeout documents.",
        "Maintain a log of submittals, Requests for Information (RFIs), and Potential Change Orders.",
        "Perform other related duties as assigned by Engineering Project Manager(s).",
      ],
      qualifications: [],
    },
    {
      slug: "health-and-safety-coordinator",
      title: "Health and Safety Coordinator",
      location: "Canada",
      type: "Full-Time",
      department: "Health & Safety",
      eyebrow: "Canada Opportunity",
      summary:
        "Develop, coordinate, and maintain workplace health and safety programs that protect employees and support regulatory compliance across the organization.",
      responsibilities: [
        "Program Management: Develop, implement, and maintain health and safety policies, procedures, and training programs.",
        "Risk Assessment & Audits: Conduct regular workplace inspections, ergonomic assessments, and safety audits to identify and mitigate hazards.",
        "Incident Investigation: Lead investigations into accidents, near misses, and safety concerns to determine root causes and implement corrective actions.",
        "Training & Communication: Provide comprehensive safety training to employees, including new-hire orientations, and maintain training records.",
        "Compliance: Ensure the organization adheres to all federal, provincial, and local health and safety regulations.",
        "Reporting: Prepare detailed reports on safety performance, audit findings, and recommended corrective actions.",
        "Collaboration: Work with managers, employees, and Joint Health & Safety Committees (JHSCs) to promote a safe work environment.",
        "Documentation: Maintain and update all health and safety-related documents, forms, and digital systems.",
        "Workplace Inspections: Regularly inspect workplace locations to ensure safety and compliance.",
        "Risk Management: Develop and implement strategies to prevent accidents and occupational injuries.",
        "Training Coordination: Schedule and organize safety training sessions and coordinate online training modules.",
        "Record Keeping: Track and maintain records of training, incidents, and safety data.",
        "Supplier/Contractor Audits: Conduct audits of suppliers and contractors to ensure they meet safety standards.",
        "Safety Promotion: Promote health and safety awareness and initiatives throughout the organization.",
      ],
      qualifications: [],
    },
    {
      slug: "material-handler-shipping-clerk",
      title: "Material Handler / Shipping Clerk",
      location: "Canada",
      type: "Full-Time",
      department: "Shipping & Receiving",
      eyebrow: "Canada Opportunity",
      summary:
        "The Material Handler / Shipping Clerk is responsible for the safe and efficient movement, handling, identification, storage, preparation, and shipment of materials, components, finished products, and equipment throughout the manufacturing facility. The position ensures that shipments are accurately prepared, properly packaged, documented, loaded, and delivered according to customer requirements and company procedures.",
      sections: [
        {
          title: "Material Handling",
          items: [
            "Receive, move, organize, and stage raw materials, fabricated components, and finished products.",
            "Verify materials against work orders, purchase orders, packing slips, and shipping documentation.",
            "Identify and properly label materials and products.",
            "Maintain organized material storage areas and ensure materials are readily accessible.",
            "Supply materials and components to production areas as required.",
            "Safely handle steel, aluminum, fabricated components, pallets, crates, and other industrial materials.",
            "Operate material-handling equipment such as forklifts, pallet jacks, overhead cranes, and other equipment when trained and authorized.",
            "Report damaged, missing, incorrect, or questionable materials to the appropriate supervisor.",
          ],
        },
        {
          title: "Shipping",
          items: [
            "Prepare customer orders for shipment according to shipping instructions and delivery requirements.",
            "Verify quantities, part numbers, job numbers, dimensions, and identification before shipment.",
            "Package, band, wrap, crate, or otherwise secure products for transportation.",
            "Prepare shipping labels, packing slips, bills of lading, and other required documentation.",
            "Coordinate with carriers and drivers regarding pickups and deliveries.",
            "Load trucks and trailers safely and efficiently.",
            "Verify that the correct materials and products are loaded onto the correct vehicle.",
            "Obtain and maintain required shipping documentation and delivery confirmations.",
            "Communicate shipping delays or problems to the Shipping Supervisor or appropriate management personnel.",
          ],
        },
        {
          title: "Receiving",
          items: [
            "Assist with receiving incoming materials, supplies, and equipment.",
            "Inspect incoming shipments for visible damage and quantity discrepancies.",
            "Compare received materials against purchase orders and delivery documentation.",
            "Report discrepancies, shortages, or damaged goods immediately.",
            "Ensure received materials are properly identified, tagged, and stored.",
          ],
        },
        {
          title: "Inventory and Documentation",
          items: [
            "Maintain accurate records of material movement and shipments.",
            "Assist with inventory counts and material reconciliation.",
            "Ensure job numbers and material identification remain accurate throughout the handling process.",
            "Complete shipping and receiving paperwork accurately and on time.",
            "Assist with investigating discrepancies between physical inventory and company records.",
          ],
        },
        {
          title: "Safety Responsibilities",
          items: [
            "Follow all company health and safety policies and procedures.",
            "Comply with the Ontario Occupational Health and Safety Act and applicable regulations.",
            "Wear required personal protective equipment (PPE).",
            "Perform pre-use inspections of forklifts, cranes, lifting devices, and other equipment before operation.",
            "Never operate equipment without proper training and authorization.",
            "Follow proper lifting, rigging, loading, unloading, and material-handling procedures.",
            "Keep aisles, emergency exits, fire equipment, and designated travel lanes clear.",
            "Immediately report unsafe conditions, damaged equipment, spills, injuries, or near misses.",
            "Ensure loads are properly secured before transportation.",
            "Maintain good housekeeping in shipping, receiving, and material storage areas.",
          ],
        },
        {
          title: "Equipment",
          description:
            "The employee may be required to operate or work around the following equipment. Only employees who have received the required training and authorization may operate applicable equipment.",
          items: [
            "Forklifts.",
            "Pallet jacks.",
            "Overhead cranes.",
            "Hoists and lifting devices.",
            "Strapping and banding equipment.",
            "Packaging equipment.",
            "Hand and power tools.",
            "Shipping and inventory computer systems.",
          ],
        },
        {
          title: "Qualifications",
          items: [
            "Previous experience in shipping, receiving, warehousing, material handling, or a manufacturing environment is preferred.",
            "Forklift certification is an asset.",
            "Experience operating overhead cranes or other lifting equipment is an asset.",
            "Ability to read shipping documents, work orders, packing slips, and material identification.",
            "Basic computer skills.",
            "Good organizational and communication skills.",
            "Ability to work independently and as part of a team.",
            "Ability to safely lift and move materials within the requirements of the position.",
            "Manufacturing or metal-fabrication experience is an asset.",
          ],
        },
        {
          title: "Physical Requirements",
          description: "The position may require the employee to:",
          items: [
            "Stand and walk for extended periods.",
            "Lift, carry, push, and pull materials and equipment.",
            "Work around heavy machinery and industrial equipment.",
            "Work indoors and outdoors as required.",
            "Work in varying temperatures and environmental conditions.",
            "Climb stairs, ladders, or access loading areas where required.",
            "Wear required safety footwear, eye protection, hearing protection, and other PPE.",
          ],
        },
        {
          title: "Skills and Competencies",
          description: "The successful candidate should demonstrate:",
          items: [
            "Strong attention to detail.",
            "Safety-conscious work habits.",
            "Good organizational skills.",
            "Ability to accurately identify materials and products.",
            "Reliability and punctuality.",
            "Ability to prioritize multiple shipping and material-handling requirements.",
            "Good communication skills.",
            "Ability to work under time constraints.",
            "Ability to follow written and verbal instructions.",
            "Ability to identify and report problems before they result in shipping or production errors.",
          ],
        },
        {
          title: "Performance Expectations",
          description: "The Material Handler / Shipping Clerk is expected to:",
          items: [
            "Maintain accurate shipping and receiving documentation.",
            "Ensure the correct material and products are shipped to the correct customer or job.",
            "Maintain organized shipping and storage areas.",
            "Handle all materials safely and appropriately.",
            "Follow all company safety rules and procedures.",
            "Minimize shipping errors, damage, and delays.",
            "Maintain accurate inventory and material movement records.",
            "Communicate problems promptly to management.",
            "Maintain professional and respectful relationships with coworkers, customers, suppliers, and transportation providers.",
          ],
        },
        {
          title: "Working Relationships",
          description:
            "The Material Handler / Shipping Clerk works closely with:",
          items: [
            "Shipping and Receiving.",
            "Production Supervisors.",
            "Shop Foremen.",
            "Production Employees.",
            "Purchasing.",
            "Project Management.",
            "Quality Control.",
            "Drivers and transportation companies.",
            "Suppliers and customers.",
          ],
        },
      ],
    },
    {
      slug: "manufacturing-planner-production-scheduler",
      title: "Manufacturing Planner / Production Scheduler",
      location: "Canada",
      type: "Full-Time",
      department: "Production Planning",
      eyebrow: "Canada Opportunity",
      summary:
        "The Manufacturing Planner is responsible for developing, maintaining, and optimizing production schedules to ensure on-time delivery, efficient use of resources, and alignment with customer demand. This role coordinates closely with production, procurement, engineering, and logistics to balance capacity, materials, and labor while minimizing downtime and inventory costs.",
      sections: [
        {
          title: "Key Responsibilities",
          items: [
            "Develop and maintain detailed short- and long-term production schedules.",
            "Translate customer demand, forecasts, and sales orders into executable manufacturing plans.",
            "Monitor capacity, labor availability, and equipment constraints.",
            "Coordinate material availability with procurement and inventory teams.",
            "Adjust schedules in response to changes such as demand fluctuations, material shortages, or equipment issues.",
            "Track production progress and update schedules accordingly.",
            "Communicate schedule priorities and changes clearly to production teams.",
            "Identify bottlenecks and recommend process or scheduling improvements.",
            "Ensure schedules support on-time delivery and inventory targets.",
            "Maintain accurate planning data in ERP/MRP systems.",
            "Support continuous improvement initiatives related to planning and scheduling.",
          ],
        },
        {
          title: "Required Qualifications",
          items: [
            "Bachelor's degree in Supply Chain, Manufacturing, Operations, or a related field, or equivalent experience.",
            "2–5+ years of experience in manufacturing planning or production scheduling.",
            "Proficiency in Excel and planning tools.",
            "Knowledge of manufacturing processes and capacity planning.",
            "Strong analytical and problem-solving skills.",
          ],
        },
        {
          title: "Preferred Qualifications",
          items: [
            "Experience in lean manufacturing or continuous improvement environments.",
            "Experience with cross-functional planning in a high-mix or high-volume environment.",
          ],
        },
        {
          title: "Key Skills & Competencies",
          items: [
            "Excellent organizational and time-management skills.",
            "Ability to manage competing priorities under tight deadlines.",
            "Strong communication and collaboration skills.",
            "Detail-oriented with a big-picture mindset.",
            "Data-driven decision-making.",
          ],
        },
        {
          title: "Work Environment",
          items: [
            "Manufacturing and office-based setting.",
            "Frequent interaction with production floor personnel.",
            "May require occasional overtime to support production demands.",
          ],
        },
      ],
    },
    {
      slug: "purchasing-agent",
      title: "Purchasing Agent",
      location: "Canada",
      type: "Full-Time",
      department: "Purchasing",
      eyebrow: "Canada Opportunity",
      summary:
        "The Purchasing Agent is responsible for procuring materials, supplies, equipment, and services for operations while managing suppliers and supporting production requirements in a fast-paced, high-volume environment.",
      sections: [
        {
          title: "Key Responsibilities",
          items: [
            "Procure materials, supplies, equipment, and services for operations.",
            "Review requisition requests, prepare purchase orders, and solicit bids for materials and services.",
            "Apply strong knowledge of Material Test Reports (MTRs) from metal suppliers.",
            "Read and understand engineering drawings, including dimensioning and tolerancing.",
            "Apply a quality-assurance background gained in an environment with established quality standards.",
            "Remain accountable for all purchasing activities and supplier management in a fast-paced, high-volume environment.",
            "Process purchase requisitions and issue purchase orders for products and services based on negotiated costs and deliverables.",
            "Manage a portfolio of materials and suppliers to ensure product-manufacturing targets are met.",
            "Ensure the continuous supply of required goods and materials, and communicate any supply problems that may pose a risk to or affect business operations.",
            "Identify new or alternate sources of supply while maintaining alignment with the long-term supply-chain strategy.",
            "Work cross-functionally across the organization and with suppliers to resolve issues related to material supply, costs, and purchase-order-to-invoice discrepancies.",
            "Coordinate shipments and receive and track deliveries.",
            "Perform all other duties as assigned.",
          ],
        },
        {
          title: "Qualifications & Key Competencies",
          items: [
            "Bachelor of Science in Business Administration or a related field, or equivalent working experience.",
            "2–3 years of sales- or purchasing-related experience in the metals industry is an asset.",
            "Experience or knowledge in the metals industry is desirable.",
            "Strong Microsoft Office application skills, including Excel and Word.",
            "Excellent customer-service and interpersonal skills, with the ability to communicate effectively both verbally and in writing.",
            "Strong team player with the ability to build collaborative relationships with Sales, Shipping & Receiving, Production, suppliers, and customers.",
            "Self-motivated, with strong organizational skills and the ability to prioritize tasks in a fast-paced environment.",
            "Ability to work under pressure and meet deadlines.",
            "Strong analytical skills, high attention to detail, and the ability to follow policies and procedures.",
          ],
        },
      ],
    },
    {
      slug: "human-resources-manager",
      title: "Human Resources Manager",
      location: "Canada",
      type: "Full-Time",
      department: "Human Resources",
      eyebrow: "Canada Opportunity",
      summary:
        "The Human Resources Manager is responsible for managing and coordinating the Company's human resources functions, policies, programs, and employee relations activities. The position provides guidance to management and employees on workplace policies, recruitment, compensation and benefits, performance management, attendance, discipline, training, health and safety, employment standards, and other employment-related matters. The Human Resources Manager is expected to promote a professional, respectful, safe, and productive workplace while ensuring that HR practices are consistently applied and comply with applicable legislation and Company policies.",
      sections: [
        {
          title: "Recruitment and Staffing",
          items: [
            "Develop and maintain recruitment procedures and processes.",
            "Prepare and post job advertisements.",
            "Review applications and conduct initial candidate screening.",
            "Coordinate interviews with hiring managers.",
            "Conduct or assist with reference and background checks where authorized.",
            "Prepare employment offers, employment agreements, and new-hire documentation.",
            "Coordinate employee onboarding and orientation.",
            "Maintain appropriate recruitment records.",
            "Monitor staffing requirements and assist management with workforce planning.",
          ],
        },
        {
          title: "Employee Relations",
          items: [
            "Act as a primary point of contact for employee HR matters.",
            "Address employee concerns, complaints, and workplace issues professionally and confidentially.",
            "Assist managers and supervisors with employee relations matters.",
            "Investigate workplace complaints and employment-related concerns as required.",
            "Facilitate communication between employees and management.",
            "Promote consistent and fair application of Company policies.",
            "Maintain appropriate documentation of employee relations matters.",
          ],
        },
        {
          title: "Performance Management",
          items: [
            "Develop and administer performance evaluation processes.",
            "Coordinate probationary, annual, and ongoing employee evaluations.",
            "Assist managers with performance management.",
            "Develop and administer Performance Improvement Plans (PIPs), where appropriate.",
            "Monitor employee performance documentation.",
            "Assist management with progressive disciplinary processes.",
            "Ensure performance and disciplinary documentation is maintained appropriately.",
          ],
        },
        {
          title: "Attendance and Leave Management",
          items: [
            "Monitor employee attendance and absenteeism.",
            "Administer vacation, statutory leave, personal leave, and other applicable leaves.",
            "Maintain appropriate attendance records.",
            "Work with managers regarding attendance concerns.",
            "Coordinate accommodation and return-to-work processes as appropriate.",
            "Maintain confidentiality of employee information.",
          ],
        },
        {
          title: "Compensation and Benefits",
          items: [
            "Assist with the administration of employee compensation programs.",
            "Coordinate payroll-related HR information and changes.",
            "Administer employee benefit programs.",
            "Coordinate employee benefit enrolment, changes, and terminations.",
            "Maintain accurate employee compensation and benefits records.",
            "Assist management with compensation reviews and salary administration.",
          ],
        },
        {
          title: "Employment Legislation and Compliance",
          items: [
            "Monitor and maintain compliance with applicable employment legislation.",
            "Maintain knowledge of applicable Ontario employment requirements, including the Employment Standards Act, 2000, Occupational Health and Safety Act, Human Rights Code, Workplace Safety and Insurance Act, and applicable privacy requirements.",
            "Maintain required employment records and documentation.",
            "Ensure Company policies and procedures are reviewed and updated as necessary.",
            "Assist management with employment-law and workplace compliance matters.",
            "Coordinate with external legal counsel or HR advisors when required.",
          ],
        },
        {
          title: "Health and Safety",
          items: [
            "Support the Company's health and safety program in cooperation with management and the Health & Safety department.",
            "Assist with employee safety training and documentation.",
            "Maintain appropriate records relating to workplace incidents and employee training.",
            "Participate in workplace investigations where required.",
            "Support the Company's health and safety policies and procedures.",
            "Assist in ensuring employees receive required workplace training and orientation.",
          ],
        },
        {
          title: "Training and Development",
          items: [
            "Identify employee training requirements.",
            "Coordinate employee orientation and onboarding training.",
            "Maintain employee training records.",
            "Assist managers in developing employee training plans.",
            "Coordinate external training providers where appropriate.",
            "Support employee development and succession planning.",
          ],
        },
        {
          title: "Policies and Procedures",
          items: [
            "Develop, implement, and maintain HR policies and procedures.",
            "Maintain the Employee Handbook.",
            "Ensure policies are communicated effectively to employees.",
            "Review policies periodically and recommend changes to management.",
            "Assist supervisors and managers in applying Company policies consistently.",
            "Maintain appropriate acknowledgement records for policies and procedures.",
          ],
        },
        {
          title: "Employee Records and Confidentiality",
          items: [
            "Maintain accurate and confidential employee personnel files.",
            "Ensure employee records are appropriately stored and protected.",
            "Maintain records relating to employment, compensation, attendance, training, performance, discipline, and termination.",
            "Control access to confidential employee information.",
            "Ensure information is disclosed only to authorized individuals and where legally appropriate.",
          ],
        },
        {
          title: "Workplace Investigations",
          items: [
            "Conduct or coordinate investigations into workplace complaints and allegations.",
            "Interview employees and relevant witnesses.",
            "Review relevant documentation and evidence.",
            "Prepare investigation documentation and reports.",
            "Make factual findings and provide recommendations to management where appropriate.",
            "Maintain confidentiality throughout the investigation process.",
          ],
        },
        {
          title: "Terminations and Offboarding",
          items: [
            "Coordinate employee resignations, layoffs, dismissals, and other employment separations.",
            "Prepare or coordinate termination documentation.",
            "Conduct exit interviews where appropriate.",
            "Coordinate recovery of Company property.",
            "Coordinate cancellation or termination of benefits and system access.",
            "Ensure required final employment documentation is completed.",
            "Maintain appropriate records of employee separation.",
          ],
        },
        {
          title: "Management Responsibilities",
          items: [
            "Provide HR guidance to managers, supervisors, and employees.",
            "Establish HR procedures and administrative controls.",
            "Supervise HR staff and administrative personnel where applicable.",
            "Manage HR projects and initiatives.",
            "Prepare HR reports and workforce metrics for senior management.",
            "Participate in management meetings as required.",
            "Recommend improvements to organizational structure, staffing, policies, and employee programs.",
          ],
        },
        {
          title: "Required Qualifications — Education",
          items: [
            "Post-secondary education in Human Resources Management, Business Administration, Industrial Relations, or a related field.",
            "CHRP/CHRL designation or progress toward designation is considered an asset.",
          ],
        },
        {
          title: "Required Qualifications — Experience",
          items: [
            "Minimum 3-5 years of progressive HR experience, preferably in a manufacturing, industrial, construction, or other hands-on workplace environment.",
            "Experience managing employee relations and workplace investigations.",
            "Experience with recruitment, performance management, discipline, attendance management, and employee records.",
            "Experience interpreting and applying employment legislation and Company policies.",
          ],
        },
        {
          title: "Required Qualifications — Knowledge",
          items: [
            "Ontario employment legislation.",
            "Recruitment and selection practices.",
            "Employee relations.",
            "Performance management.",
            "Progressive discipline.",
            "Workplace investigations.",
            "Compensation and benefits administration.",
            "Employee training and development.",
            "Occupational health and safety requirements.",
            "HR recordkeeping and confidentiality.",
          ],
        },
        {
          title: "Required Skills and Competencies",
          items: [
            "Strong communication and interpersonal skills.",
            "Professional judgment and discretion.",
            "Excellent organizational and administrative skills.",
            "Strong conflict-resolution skills.",
            "Ability to maintain confidentiality.",
            "Strong investigation and fact-finding skills.",
            "Ability to interpret policies and legislation.",
            "Strong documentation and report-writing skills.",
            "Ability to work independently and make sound recommendations.",
            "Ability to work effectively with employees at all organizational levels.",
            "Strong computer and HRIS skills.",
            "Ability to manage multiple priorities and deadlines.",
          ],
        },
        {
          title: "Personal Attributes",
          items: [
            "Integrity and professionalism.",
            "Confidentiality and discretion.",
            "Fair and consistent treatment of employees.",
            "Sound judgment.",
            "Accountability.",
            "Reliability.",
            "Respectful communication.",
            "Strong problem-solving ability.",
            "A practical, business-oriented approach to HR.",
            "Ability to remain objective during workplace disputes and investigations.",
          ],
        },
        {
          title: "Key Performance Indicators",
          items: [
            "Recruitment effectiveness and time-to-fill.",
            "Employee retention and turnover.",
            "Accuracy and completeness of employee records.",
            "Timely completion of employee documentation.",
            "Completion of employee onboarding and training.",
            "Effectiveness of performance-management processes.",
            "Timely handling of employee relations matters.",
            "HR policy compliance.",
            "Benefits and payroll administration accuracy.",
            "Training-record compliance.",
            "Quality and timeliness of HR reporting.",
            "Management and employee satisfaction with HR support.",
          ],
        },
        {
          title: "Authority and Decision-Making",
          items: [
            "The Human Resources Manager is authorized to administer approved HR policies and procedures and provide recommendations to management.",
            "The Human Resources Manager does not have authority to independently make decisions involving significant compensation changes, hiring outside approved staffing requirements, termination of employment, or other matters reserved for senior management unless specifically authorized.",
          ],
        },
        {
          title: "Working Conditions",
          items: [
            "The position may require work in both an office and manufacturing/shop environment.",
            "When entering or working in production areas, the Human Resources Manager must comply with all applicable Company safety requirements, including required personal protective equipment, access restrictions, and workplace safety procedures.",
          ],
        },
        {
          title: "Confidentiality",
          items: [
            "The Human Resources Manager will have access to confidential employee, payroll, compensation, medical/accommodation, disciplinary, business, and Company information.",
            "All such information must be handled in accordance with Company policies, applicable privacy requirements, and the employee's duties of confidentiality.",
          ],
        },
      ],
    },
  ],
  us: [
    {
      slug: "metal-fabricator",
      title: "Metal Fabricator",
      location: "New York, United States",
      type: "Full-Time",
      department: "Welding & Fabrication",
      eyebrow: "United States Opportunity",
      summary:
        "Mariani is seeking a metal fabricator to support the production of custom architectural metalwork for complex projects across the United States.",
      responsibilities: [
        "Read fabrication drawings and prepare materials for production.",
        "Cut, fit, form, assemble, and finish metal components accurately.",
        "Verify dimensions and quality at each stage of fabrication.",
        "Use tools and equipment safely and maintain an organized work area.",
        "Coordinate with supervisors, welders, and quality-control personnel.",
      ],
      qualifications: [
        "Previous metal-fabrication or architectural-metalwork experience.",
        "Ability to read drawings and work from precise measurements.",
        "Working knowledge of common fabrication tools and equipment.",
        "Reliable, safety-focused, and comfortable working within a team.",
      ],
    },
    {
      slug: "quality-control-inspector",
      title: "Quality Control Inspector",
      location: "New York, United States",
      type: "Full-Time",
      department: "Quality Control & Inspection",
      eyebrow: "United States Opportunity",
      summary:
        "Mariani is seeking a quality control inspector to verify materials, fabrication, dimensions, finishes, and documentation against project requirements.",
      responsibilities: [
        "Inspect incoming materials, fabricated components, welds, and assemblies.",
        "Verify work against drawings, specifications, tolerances, and quality plans.",
        "Document inspection results and coordinate corrective actions.",
        "Support traceability, reporting, and quality-system requirements.",
        "Work with production teams to prevent recurring quality issues.",
      ],
      qualifications: [
        "Quality-control or inspection experience in fabrication or manufacturing.",
        "Ability to interpret drawings, specifications, and measurement requirements.",
        "Experience using inspection and precision-measurement tools.",
        "Relevant inspection or welding certifications are considered an asset.",
      ],
    },
  ],
};

export const getCareerDetail = (region, slug) => {
  const job = JOBS_BY_REGION[region]?.find((item) => item.slug === slug);

  if (job) {
    return {
      ...job,
      kind: "job",
    };
  }

  const area = CAREER_AREAS.find((item) => item.slug === slug);

  if (area) {
    return {
      ...area,
      kind: "area",
      location: region === "us" ? "United States" : "Canada",
      type: "Career Area",
      department: area.title,
    };
  }

  return null;
};
